name: test cron

on:
  schedule:
    - cron: '17 1 1 1 *'

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: do a pwd
        run: |
          pwd
          ls -l
          
