name: test cron

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        run: actions/checkout@v3

      - name: do a pwd
        run: |
          pwd
          ls -l
          
