# This workflow will install Python dependencies and run tests with a single version of Python
name: Python unit test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  conors_unit_test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   
    - name: Test with pytest from within the dashapp directory
      working-directory: dashapp
      run: |
        pytest
